### ISSUE TITLE
Rs rotation at bit level or at byte level?

### ISSUE THREAD

**Issue by ebenayas** [mitshell/CryptoMobile#10]
I have a question about rot_buf method (on Milenage.py file):

According to standard:
rot(x,r)                   The result of cyclically rotating the 128-bit value x by r bit positions towards the most significant bit. If x = x[0] || x[1] || … x[127], and y = rot(x,r), 
then y = x[r] || x[r+1] || … x[127] || x[0] || x[1] || x[r-1]. 
it seems that Rs rotation should be made at bit level. However, here the Rs rotation is made at byte level… what provides the same result if R is a multiple of 8, but the diferent result if R is not multiple of 8

def rot_buf(b, r):

    """rotate buffer b by r bits, r must be an 8-bit multiple"""

    r //= 8

    return b[r:] + b[:r]

I have not found anything (on standard) telling R must be multiple of 8. So that,  maybe the solution should be something like this:

def rot_buf(b, r):

   """rotate buffer b by r bits"""
    c = BitArray(b)
    return (c[r:] + c[:r]).bytes

**Comment by mitshell** [comment]
You are correct that the rotation should not be limited to 8 bits multiple.
Regarding your potential patch: could you provide something that does not rely on 3rd party library or package, but only on Python built-ins ?

**Comment by ebenayas** [comment]
Hi, 

A posible solution using only Python built-ins could be:

def rot_buf(b, r):
    """rotate buffer b by r bits"""
    if ( (r%8) != 0 ):
        c = ''.join(format(byte, '08b') for byte in b)
        return int( c[r:] + c[:r],2).to_bytes(len(c) // 8, byteorder='big')
    else:
        r //=8
        return b[r:] + b[:r]

I check if R is a multiple of 8 in order to execute a more efficient algorithm because R is often multiple of 8, althougt it would be possible to execute  execute the first part for all cases.

BR,
Esther

**Comment by mitshell** [comment]
Thanks for your proposal.
I tried it, realized it does not work with python2, tried to optimized it a bit, and finally came up with a new `rot_buf16()` function which is really faster. Now you should be able to use non-byte-aligned rotation in Milenage straight from the repository.

**Comment by ebenayas** [comment]
I have checked your commit and now it is working fine for me. Thanks a lot for your fix
