### ISSUE TITLE
How to retrieve the actual private key from ECDH_SECP256R1.get_privkey()

### ISSUE THREAD

**Issue by lemur117** [mitshell/CryptoMobile#12]
I'm wondering how to retrieve just the value of the private key, since I'm not fully understanding how it is packaged.  Per the instructions:

```
>>> ec = ECDH_SECP256R1() # using secp256r1 elliptic curve domain, i.e. profile B
>>> ec.generate_keypair()
>>> hn_pubkey = ec.get_pubkey()
>>> hn_pubkey
b'\x03u\xe82C\xa3.\x0e)\xaf\xd6\xad\n\x01\xafZ2\xca\xc9\x95G\\xG\x9d\xdczU\x91n\x1d%m'
>>> hn_privkey = ec.get_privkey()
**>>> hn_privkey # the private key for secp256r1 is longer as it actually packages both private and public keys into a X.509 DER-encoded buffer**
b"0\x81\x87\x02\x01\x000\x13\x06\x07*\x86H\xce=[...]\x86'\x17"
```

And per the interactive help output of help(ECDH_SECP256R1):

```
Help on class ECDH_SECP256R1 in module CryptoMobile.EC:

class ECDH_SECP256R1(builtins.object)
 |  ECDH_SECP256R1(loc_privkey=None, _raw_keypair=None)
 |  
 |  wrapper around Python cryptography library to handle an ECDH  exchange over 
 |  a NIST secp256r1 elliptic curve
 |  
 **|  private key is handled within a DER-encoded PKCS8 structure**
 |  public key is handled as a compressed point bytes buffer according to ANSI X9.62

```

How is it both "X.509 DER encoded" and "PKCS8 DER encoded?"  

This is how far I've gotten in retrieving the value of the private key, but I don't think it's right yet:

```
>>> import asn1
>>> from Crypto.IO.PKCS8 import unwrap
>>> import binascii
>>> from CryptoMobile.EC import *
>>> ec_B = ECDH_SECP256R1()
>>> ec_B.get_privkey()
b'0\x81\x87\x02\x01\x000\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x04m0k\x02\x01\x01\x04 Wj\x80L\t\xc5\xa1oW\xd9\xbbFs{TH\xea\xe1*\x9a\x95\xf6\xe1\xd1\xe1\x9a%\xc8\xb7\xb3~h\xa1D\x03B\x00\x04\xf0T\xear^x\xb6\xa8\xe8\x04T \xf1\xbe\x81\xac\xba\xfdJ\xa10Y_\x0b\xb5^\x140\xaf\xa1S\x14|@\xfaV\x08\x15\x05Cr\xa7\xd1F\xcevq(H\x8a\x8d\xa2\xce\x84\xaa<\x0b>\xf5\xe0\xf1\xed\x9f\x90'
>>> unwrap(ec_B.get_privkey())
('1.2.840.10045.2.1', b'0k\x02\x01\x01\x04 Wj\x80L\t\xc5\xa1oW\xd9\xbbFs{TH\xea\xe1*\x9a\x95\xf6\xe1\xd1\xe1\x9a%\xc8\xb7\xb3~h\xa1D\x03B\x00\x04\xf0T\xear^x\xb6\xa8\xe8\x04T \xf1\xbe\x81\xac\xba\xfdJ\xa10Y_\x0b\xb5^\x140\xaf\xa1S\x14|@\xfaV\x08\x15\x05Cr\xa7\xd1F\xcevq(H\x8a\x8d\xa2\xce\x84\xaa<\x0b>\xf5\xe0\xf1\xed\x9f\x90', b'\x06\x08*\x86H\xce=\x03\x01\x07')
>>> 
>>> 
>>> decoder = asn1.Decoder()
>>> decoder.start(unwrap(ec_B.get_privkey())[1])
>>> tag, value = decoder.read()
>>> tag
Tag(nr=16, typ=32, cls=0)
>>> value
b'\x02\x01\x01\x04 Wj\x80L\t\xc5\xa1oW\xd9\xbbFs{TH\xea\xe1*\x9a\x95\xf6\xe1\xd1\xe1\x9a%\xc8\xb7\xb3~h\xa1D\x03B\x00\x04\xf0T\xear^x\xb6\xa8\xe8\x04T \xf1\xbe\x81\xac\xba\xfdJ\xa10Y_\x0b\xb5^\x140\xaf\xa1S\x14|@\xfaV\x08\x15\x05Cr\xa7\xd1F\xcevq(H\x8a\x8d\xa2\xce\x84\xaa<\x0b>\xf5\xe0\xf1\xed\x9f\x90'
>>> print(binascii.hexlify(value))
b'0201010420576a804c09c5a16f57d9bb46737b5448eae12a9a95f6e1d1e19a25c8b7b37e68a14403420004f054ea725e78b6a8e8045420f1be81acbafd4aa130595f0bb55e1430afa153147c40fa560815054372a7d146ce767128488a8da2ce84aa3c0b3ef5e0f1ed9f90'
```

The hexlified version of "value" seems to be much too large for a private key.  Do I need to do something further with that?  Or is that the public key, as would be indicated by the oid: '1.2.840.10045.2.1.'  If so, what would I need to do to get the private key?

**Comment by mitshell** [comment]
Thanks for your feedback.
The text in the README is actually wrong, and should read "DER-encoded PKC8 structure" and not X.509. Thanks for pointing this out.

Regarding the private key with ECDH_SECP256R1, the API to manipulate public and private keys is not as straightforward as with Curve25519. If you want to store and reload the private key, after generating it, its better and easier to use the method `get_privkey()` which output can be reused within the `__init__()` of another instance.

In your case, the private key is under the `ec_B.PrivKey` attribute, which is an object that wraps the OpenSSL Elliptic Curve implementation. It has 2 methods to access the private key: `private_bytes()` and `private_numbers()`.
This is documented here: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKeyWithSerialization

In case you want to load raw public / private SEC256P1 keypairs, you can check the code that implements the test vectors:
https://github.com/mitshell/CryptoMobile/blob/c449eb45a7e7a52b5984554ba813ae0dd50be00e/test/test_ECIES.py#L74
