### ISSUE TITLE
error on unprotect

### ISSUE THREAD

**Issue by veenone** [mitshell/CryptoMobile#14]
Hello,

I was trying to thest the ProfileB for ECIES library and it's not working with the following error :

`CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
Traceback (most recent call last):
  File "C:\git\CryptoMobile\CryptoMobile\mypy.py", line 30, in <module>
    ue_pk, ue_ct, ue_mac = ue.protect(plaintext)
  File "C:\Python35\lib\site-packages\CryptoMobile\ECIES.py", line 92, in protect
    aes = AES_CTR(aes_key, aes_nonce, aes_cnt)
  File "C:\Python35\lib\site-packages\CryptoMobile\AES.py", line 145, in __init__
    counter=self.__cnt)
  File "C:\Python35\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Python35\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Python35\lib\site-packages\Crypto\Cipher\_mode_ctr.py", line 366, in _create_ctr_cipher
    _counter = dict(counter)
TypeError: 'method' object is not iterable`

I'm using Python 3.5.4 and cryptography 3.2.1

anything I missed ? or am I using the wrong version?

**Comment by p1-bmu** [comment]
Thanks for your report.
1) According to the readme, it is better to use the fork at P1Sec: https://github.com/P1sec/CryptoMobile than this version.
2) You should try to format your error messages in a more readable way.
3) You should explain clearly what you did, and what code triggers this error. Next time please provide your full code extract that reproduces this error.
4) From the provided stacktrace, it seems you may have some version of pycryptodome installed in your system (in _C:\Python35\lib\site-packages\Crypto\Cipher\AES.py_). Pycryptodome broke the calling convention of the counter mode (CTR) encryption, from the original pycrypto library ; therefore if you want to use pycryptodome, you should better install the _pycryptodomex_ package, which does not masquerade the original pycrypto library.
Ultimately, you can enable / disable AES backend here: https://github.com/P1sec/CryptoMobile/blob/5c01a9f887e9d92dc85c86abbd55f569482326d1/CryptoMobile/AES.py#L70
