### ISSUE TITLE
How to generate public key from private key for Profile B

### ISSUE THREAD

**Issue by lemur117** [mitshell/CryptoMobile#16]
I'm trying to understand how to generate a home network public key if supplied with the private key for the "Profile B" method.  I can get the "Profile A" method's public key from the private key in the following way:

```
from CryptoMobile.EC import *
import binascii
priv_key=b'c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d'
priv_key_bytes=binascii.unhexlify(priv_key)
ec = X25519(loc_privkey=priv_key_bytes)
pub_key_bytes=ec.get_pubkey()
pub_key=binascii.hexlify(pub_key_bytes)
print(pub_key)

```
Output:
`>>> 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650`

The output matches the expected public key from 3GPP TS 33.501 version 15.5.0 Release 15, Annex C.4.3 "ECIES Profile A"
But if I try similar for Profile B, I get an error, as below.

```
>>> privkey_B = b'F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA'
>>> privkey_B_bytes = binascii.unhexlify(privkey_B)
>>> ec = ECDH_SECP256R1(loc_privkey=privkey_B_bytes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Python/venv/py38/lib/python3.8/site-packages/CryptoMobile/EC.py", line 92, in __init__
    self.PrivKey = serialization.load_der_private_key(
  File "/home/user/Python/venv/py38/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 33, in load_der_private_key
    return backend.load_der_private_key(data, password)
  File "/home/user/Python/venv/py38/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1300, in load_der_private_key
    return self._load_key(
  File "/home/user/Python/venv/py38/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1475, in _load_key
    self._handle_key_loading_error()
  File "/home/user/Python/venv/py38/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1517, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

```

Do I need to do some kind of encoding of the private key first?

**Comment by mitshell** [comment]
The API for SECP256R1 elliptic curve is not supporting the independent handling of public and private keys, as expected from the 3GPP specification. But there is a mean to do it, visible in the implementation of the test vectors:
https://github.com/mitshell/CryptoMobile/blob/5bcd996a1c0fc41d4d1c3b8fb69db15eb88ba810/test/test_ECIES.py#L85

**Comment by lemur117** [comment]
Thanks mitshell.  The examples from the test vectors require both the private key and the public key to be known, as in the case of `hn = ECIES_HN(None, profile='B', _raw_keypair=(hn_privkey, hn_pubkey))`.  After doing `ec = ECDH_SECP256R1(loc_privkey=privkey_B_bytes)` I was hoping to run `ec.get_pubkey()` to generate and retrieve the public key having only the private key as input.  Is it possible to generate and retrieve the public key using ECDH_SECP256R1?

Also, do you know how can I convert between the data type in 3GPP TS 33.501 version 15.5.0 (e.g. F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA) and the "DER-encoded PKCS8 structure?"

```
Help on class ECDH_SECP256R1 in module CryptoMobile.EC:

class ECDH_SECP256R1(builtins.object)
 |  ECDH_SECP256R1(loc_privkey=None, _raw_keypair=None)
 |  
 |  wrapper around Python cryptography library to handle an ECDH  exchange over 
 |  a NIST secp256r1 elliptic curve
 |  
 |  private key is handled within a DER-encoded PKCS8 structure
 |  public key is handled as a compressed point bytes buffer according to ANSI X9.62
 |  
 |  Methods defined here:
 |  
 |  __init__(self, loc_privkey=None, _raw_keypair=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  generate_keypair(self)
 |  
 |  generate_sharedkey(self, ext_pubkey)
 |  
 |  get_privkey(self)
 |  
 |  get_pubkey(self)
 |  


```

**Comment by mitshell** [comment]
OK, I did not get your exact question at first.
I am no ECC expert, but I can try to provide some details according to my understanding.

With SECP256R1, the private key is meaningless without the public key. So you always need to have the public key together with the private key (this is why the default format for the private key is a DER-packed structure which actually contains both the private and public keys), and I don't believe you can retrieve de public key from the private key only.

Regarding the conversion of 3GPP provided test values to a DER-packed value, I think you can use somthing like :
```
hn = ECIES_HN(None, profile='B', _raw_keypair=(hn_privkey, hn_pubkey))
k = hn.get_privkey()
```
This is using the `cryptography` ECC routines under the hood, so I can't say what transform is exactly happening here.

**Comment by lemur117** [comment]
After some further digging in the cryptography source code, I found it is possible to derive the Profile B public key from the private key.  E.g.

    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives import asymmetric

    priv_key = 'F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA'
    privkey_int = int(priv_key, base=16)
    privkey_ec = asymmetric.ec.derive_private_key(privkey_int, asymmetric.ec.SECP256R1())
    pubkey_ec = privkey_ec.public_key()
    pubkey_bytes = pubkey_ec.public_bytes(
        encoding=serialization.Encoding.X962, 
        format=serialization.PublicFormat.CompressedPoint
    )
    print(binascii.hexlify(pubkey_bytes).decode('utf-8'))
    '0272DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD1'

**Comment by mitshell** [comment]
Thanks a lot for your feedback.

**Comment by mitshell** [comment]
I finally decided to align this ECIES profile B API on profile A, thanks to the hints you provided in the issue. Now closing this !
