### ISSUE TITLE
How to compute RES* from RES for 5G SA authentication

### ISSUE THREAD

**Issue by hima-devsecops** [mitshell/CryptoMobile#17]
Hello Everyone,
I'm trying to test the 5G SA authentication procedure and struggling with generating RES*. I just started exploring Milenage and am not sure whether that is supported.

I appreciated to guide me through this, and if it's not supported, It will be great to give me some tips on where to start, thanks.

Note: 
 According to 3GPP TS33_501. RES* value is generated from RES, RAND, length of RAND, length of RES,  serving network name, and length of SNN,  using the key concatenated of CK || IK.

**Comment by hima-devsecops** [comment]
I found the way to calculate RES* from RES using `conv_501_A4` from conv.py

Thanks

**Comment by mitshell** [comment]
Excellent !
