### ISSUE TITLE
Decipher 4G NAS messages

### ISSUE THREAD

**Issue by aman75972** [mitshell/CryptoMobile#18]
Hi!. I have to decipher NAS messages which are ciphered using EIA1 (Snow-3g) based algorithm. Which function should I use and how can retrieve parameters for that function? Your response will be hugely appreciated.

**Comment by mitshell** [comment]
I guess you should go through the README and eventually the docstrings. Where the NAS decryption parameters come from is detailed in the 3GPP LTE security specification: TS 33.401.
