### ISSUE TITLE
Wrong TOPc calculate when use a diferent default keccakIterations value 

### ISSUE THREAD

**Issue by JesusDonato** [mitshell/CryptoMobile#20]
Doing beneath action we obtain the same TOPc value as obtained with default value (keccakIteractions = 1)  

```
tuak = TUAK(TOP)
setattr(tuak, "KeccakIterations", 2)
```

However you can change your customize LEN_XX values as example:
`setattr(tuak, "LEN_RES", 128)`

This issue is due to make_TOPc method is a static method and it is impossible to use the keccakIterations attribute from object so that the static attribute is used in TUAK.py, line: 74
```
    for i in range(**TUAK.**KeccakIterations):
        INOUT = keccakp1600(INOUT)
    return INOUT[:32][::-1]
```
It seems to be always generating TOPc using keccakIterations = 1

Could you be so kind to review this problem or tell me if I'm doing something wrong?

I have done a work around moving the make_TOPc() method into the TUAK class and I've changed the calls "TUAK." by "self." and I've obtained the same results than Fabricio's app .

I attach as an attachment the code I have typed to use your custom keccakIterations and ALGONAME
Kind Regards
[TUAK_make_TOPc_method_inside_TUAK_class.txt](https://github.com/mitshell/CryptoMobile/files/10085714/TUAK_make_TOPc_method_inside_TUAK_class.txt)

**Comment by p1-bmu** [comment]
Thanks for your feedback. Unfortunately, I fail to understand exactly what is your intention here.

Those class attributes of the TUAK class: 
```
    ALGONAME = b'TUAK1.0'
    
    KeccakIterations = 1
    
    ####################
    # OPERATOR SETTING #
    ####################
    # defined operator settings for the length of the differents outputs
    LEN_MAC  = 64  # can be 64, 128 or 256 bit
    LEN_RES  = 64  # can be 32, 64, 128 or 256 bit
    LEN_CK   = 128 # can be 128 or 256 bit
    LEN_IK   = 128 # can be 128 or 256 bit
    # input length for K: 128 or 256 bit
    # input length for TOP: 256 bit
```
are not expected to be changed within several computations of a given application relying on TUAK.

So, if you want 2 iterations, you can just configure the class attribute accordingly:
```
TUAK.KeccakIterations = 2
```

When you call the function `make_TOPc()`, it will rely on the TUAK configuration to compute its output.
Maybe what you are missing is an additional arg in the `make_TOPc()` input, to explicitely pass the number of Keccak iteration you want ? Or are you expecting something else ?

**Comment by JesusDonato** [comment]
Hi!, thanks a lot for your support.
Sorry for not explaining myself well.

I am making use of this library from a script in which I am testing the generation of quintets with different values of keccakIterations, different values of LEN_XX and in the future with different values of ALGONAME.
 
`from CryptoMobile.TUAK import TUAK`

The idea is to create automatic tests in which different values of these variables are assigned without having to do it manually.

Answering your question about a new argument (keccakIteractions) in the make_TOPc() method I think it would not be enough because in all the fXXX() methods are using the TUAK.keccakIterations and TUAK.ALGONAME variables and the quintets calculation would not be done correctly because it would be using the default value again.

```
        INOUT.append( TUAK.ALGONAME[::-1] )

        for i in range(TUAK.KeccakIterations):
            INOUT = keccakp1600(INOUT)
        return INOUT[:off][::-1]
```

I attached a possible solution in my first post, I don't know if you could take a look at it.

Best Regards

**Comment by mitshell** [comment]
OK, I get it. This should solve the issue: https://github.com/mitshell/CryptoMobile/commit/233af5aabdb7fdd247e91855643a9916b5d8f839

**Comment by JesusDonato** [comment]
Hi Mitshell, first of all thanks a lot for your work.

I have tried your patch but I got some errors.
```
  mac           = get_bin_hex(Tuak.f1(key, rand, sqn, amf))
  File "/usr/lib/python3.10/site-packages/CryptoMobile/TUAK.py", line 159, in f1
    TOPc = self.make_TOPc(K, TOP)
  AttributeError: 'TUAK' object has no attribute 'make_TOPc
```

The same problem with TUAK.ALGONAME and TUAK.keccakIterations in all fXX methods

 ```
       INOUT.append( TUAK.ALGONAME[::-1] )

        for i in range(TUAK.KeccakIterations):
            INOUT = keccakp1600(INOUT)
        return INOUT[:off][::-1]
```

I have made some corrections in order to acceded to the correct object and use my customized values and it works but it seems that the solution that you have proposed force to call make_topc and set_topc. This is different behavior to design base, you didn't need to do it before.

I attach the file with my corrections

Thank you very much
Best regards
/Jesús

[TUAK_11-28.txt](https://github.com/mitshell/CryptoMobile/files/10102522/TUAK_11-28.txt)

**Comment by mitshell** [comment]
Are you sure you have properly `git pull` the last version, without any of your changes on top of it ?

**Comment by JesusDonato** [comment]
Yes!, I'm executing beneath comands:
   $CRYPTO_VERSION=233af5a 
   $ wget https://github.com/P1sec/CryptoMobile/archive/$CRYPTO_VERSION.zip 
   $ unzip $CRYPTO_VERSION.zip 
   $ rm $CRYPTO_VERSION.zip 
   $ cd CryptoMobile-* 
   $ python3 setup.py install 

I've printed a trace into TUAK.py in order to know TUAK.KeccakIterations value in f1 method for example 

```
        def f1(self, K, RAND, SQN, AMF, TOP=None):
        """return MAC_A [8, 16 or 32 bytes buffer] or None on error
        """
        print("f1 method TUAK.KeccakIteration %s" % TUAK.KeccakIterations)
```
As you know I'm customizing KeccakIterations to "2" 

```
tuak = TUAK(TOP)
setattr(tuak, "KeccakIterations", 2)
```

but inside f1 TUAK.KeccakIterations continue be 1 because is using other , the TUAK object not self.KeccakIterations

`f1 method TUAK.KeccakIteration 1`

Have you been able to compare my file (TUAK_11-28.txt) with yours (TUAK.py)?

Kind Regards
/Jesús

**Comment by mitshell** [comment]
If you look at the source after the last patch, you'll see that there is now a `make_topc()` method within the TUAK class, in addition to the `make_TOPC()` function which has 2 additional parameters `ALGONAME` and `KeccakIterations`. The `make_topc()` method is used along the others methods of the class, and itself relies not on class attribute (e.g. `TUAK.KeccakIterations`...) but on instance attributes (`self.ALGONAME` and `self.KeccakIterations`).

Therefore you should probably adapt your script to get the expected result.

**Comment by JesusDonato** [comment]
Yes!, all related to make_TOPC it is clear for me but in my last comment I'm asking for `TUAK.ALGONAME` and `TUAK.KeccakIterations` inside  f1, fstar, f2345 and f5 methods, beneath lines:

_Line 132 `def f1(self, K, RAND, SQN, AMF, TOP=None):`_
- Line 164 `INOUT.append( TUAK.ALGONAME[::-1] )`
- Line 177 `for i in range(TUAK.KeccakIterations):`

_Line 181 `def f1star(self, K, RAND, SQN, AMF, TOP=None):`_
- Line 213 `INOUT.append( TUAK.ALGONAME[::-1] )`
- Line 226 `for i in range(TUAK.KeccakIterations):`

_Line 230 `def f2345(self, K, RAND, TOP=None):`_
- Line 276 `INOUT.append( TUAK.ALGONAME[::-1] )`
- Line 288 `for i in range(TUAK.KeccakIterations):`

_Line 292 `def f5star(self, K, RAND, TOP=None):`_
- Line 316 `INOUT.append( TUAK.ALGONAME[::-1] )`
- Line 328 `for i in range(TUAK.KeccakIterations):`

If you use Fabriccio's app with `keccakIterations = 2` and your code with `keccakIterations = 2` you will get **different results** but if you change in your code the lines I propose above by `self.KeccakIterations` the **results match**

**Comment by mitshell** [comment]
You're correct, I forgot to commit my last changes last time... Sorry for this, it should work properly now after the last commit (I hope so).

**Comment by JesusDonato** [comment]
Now with the last patch [e8b27fc] It is working fine!

Thanks to all for your great work and support.

Best Regards
