### ISSUE TITLE
EEA2 decrypt function ?

### ISSUE THREAD

**Issue by aswin19996** [mitshell/CryptoMobile#24]
I would like to verify the EEA2 encryption, so is there any EEA2 decryption function ? 

So my ciphertext input along with other inputs to this decryption function will fetch me the plaintext value ?

**Comment by mitshell** [comment]
EEA algorithms are working like stream ciphers, hence this is the same function working both for encrypting a plaintext, and decrypting a ciphertext. For your case, EEA2 on plaintext will generate the ciphertext, and EEA2 on the ciphertext will generate the plaintext.

**Comment by aswin19996** [comment]
Thank you for this information !
