### ISSUE TITLE
Error While Complilation

### ISSUE THREAD

**Issue by prsn1988** [mitshell/CryptoMobile#3]
[CM.txt](https://github.com/mitshell/CryptoMobile/files/779518/CM.txt)

I am running this code in my local machine and its not been compiling, I am getting errors like modules missing, path missing...
So please check the above code and let me know the mistake

**Comment by mitshell** [comment]
I guess the lib does not work over Python3.
Did you try with Python 2.7 ?

**Comment by prsn1988** [comment]
NO I HAVEN'T TRIED WITH 2.7, I WILL TRY AND WILL LET U KNOW IF THERE ARE ANY ISSUES...
THANK YOU!!!

**Comment by prsn1988** [comment]
![error](https://cloud.githubusercontent.com/assets/25717223/23054092/cc8f7566-f503-11e6-90a8-d8c156c2dad8.PNG)

HI, I HAVE INSTALLED PYTHON 2.7 AND EXECUTED, BUT I HAVE ENCOUNTERED AN ERROR...
PLEASE DO CHECK THE ABOVE SCREENSHOT AND LET ME KNOW THE PROBLEM.

**Comment by prsn1988** [comment]
![error1](https://cloud.githubusercontent.com/assets/25717223/23054224/902a0950-f504-11e6-919e-bffd25bb074b.PNG)

HI, I HAVE INSTALLED PYTHON 2.7 AND EXECUTED, BUT I HAVE ENCOUNTERED AN ERROR...
PLEASE DO CHECK THE ABOVE SCREENSHOT AND LET ME KNOW THE PROBLEM.

**Comment by mitshell** [comment]
The warning "WNG" (and the README) says you need pycrypto. I guess you did not installed it ?

**Comment by prsn1988** [comment]
YA EXACTLY, I HAVEN'T INSTALLED IT...
THANK YOU SO MUCH FOR IMMEDIATE RESPONSE...
IF YOU HAVE ANY DOCUMENTATION REGARDING THIS PROJECT CAN YOU SHARE WITH ME???
