### ISSUE TITLE
aside from comp128.c, no other code appears to indicate any license

### ISSUE THREAD

**Issue by laf0rge** [mitshell/CryptoMobile#5]
A lot of the code in this repository doesn't carry any indication of

- who is the copyright holder / author
- what is the applicable copyright license for the code

The README states there is some code taken from ETSI/3GPP reference implementation, but neither the README nor source code comments nor the commitlog appear ot indicate which of the code was taken from exactly where.

**Comment by mitshell** [comment]
Basically, all C files and headers in C_alg/ directory are taken from ETSI / 3GPP / GSMA documents, except the COMP128 one. I will update them with a comment indicating the exact file / url from which I took them. I can't do much more unfortunately.

**Comment by mitshell** [comment]
I added some commenting headers with commit https://github.com/mitshell/CryptoMobile/commit/aca2fb2719b8a620a9e114acf894e218e2d62303.
I cannot do more about the licensing.

Fun fact : 3GPP specifications for SNOW 3G and ZUC are referring to an ETSI web page that does not exist anymore (http://www.etsi.org/WebSite/OurServices/Algorithms/3gppalgorithms.aspx), where some other ETSI webpages refer to the 3GPP specifications for those algorithms (https://www.etsi.org/security-algorithms-and-codes, https://www.etsi.org/security-algorithms-and-codes/cellular-algorithm-licences)...
