### ISSUE TITLE
Is there any hope of getting SUCI?

### ISSUE THREAD

**Issue by MattEttus** [mitshell/CryptoMobile#7]
Is there any hope of getting TS 133 501 Annex C.3 going?  It is a sealed box using Curve 25519 used for SUCI in 5G.  Any pointers on how to do it?

**Comment by mitshell** [comment]
Not in the weeks to come within CryptoMobile, maybe in few months... Hard to say ! One good ECIES python implementation seems to be available here: https://ecies.org/py/. It's only for secp256k1, but if I remember correctly, this is one of the 2 profiles for SUCI encryption.

It seems harder to find some serious / documented ECIES implem with Curve25519. You may be able to start with an ECDH implem (such as https://download.libsodium.org/doc/advanced/scalar_multiplication#algorithm-details, or https://cryptography.io/en/latest/hazmat/primitives/asymmetric/x25519/#) that can be adapted to an ECIES one.

**Comment by mitshell** [comment]
Good news !
You can try the ECIES mode of operation for SUPI / SUCI protection in this fork: https://github.com/P1sec/CryptoMobile. Let me knows how it goes.

**Comment by helloworld666** [comment]
Thank you for providing the program, ECIES Profile A runs perfectly. However, using the test data of C.4.4 in the 3GPP 33501-g00.doc document, the following code is executed:
from CryptoMobile.ECIES import *
hn_privkey = bytes.fromhex('F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA')
hn = ECIES_HN(hn_privkey, profile='B')

The program throws an exception:
in _handle_key_loading_error raise ValueError("Could not deserialize key data.")
